name: Build and Release
 
on: push # when to trigger this. Here, on every push
jobs:
  build_and_test:
    name: "Build and test"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # we build on GitHub-provided Windows and Linux images
    runs-on: ${{ matrix.os }} # use value from the matrix

    permissions:
      contents: write
    
    steps:
    - name: Install dependencies (linux)
      run: sudo apt install ninja-build
      if: matrix.os == 'ubuntu-latest' # conditional, runs this step only on the Ubuntu runner
    - name: Install Ninja (windows)    # Ninja is not available in GitHub-provided images,
                                       # see https://github.com/actions/runner-images/issues/514
      run: choco install ninja         # So let's install it through Chocolatey
      if: matrix.os == 'windows-latest'
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.2'
    - uses: ilammy/msvc-dev-cmd@v1 # This action essentially calls vcvarsall.bat for the latest VS in the runner for x64
    - uses: actions/checkout@v3    # Actually check out the sources. GH Actions can run for events that may not require
                                   # sources (e.g. when someone comments on an issue)

    - name: Build
      run: mkdir ./Signal_Analyzer/Release-build_${{ matrix.os }} && cd ./Signal_Analyzer/Release-build_${{ matrix.os }} && cmake -S ../ -G "Ninja" && cmake --build ./ 
    
    - name: Packaging
      run: cd ../ && ./Qt/6.5.2/msvc2019_64/bin/windeployqt.exe ./Signal_Analyzer/Signal_Analyzer/Release-build_${{ matrix.os }}/Signal_Analyzer.exe #&& cpack -G ZIP
      if: matrix.os == 'windows-latest'
    - name: Commit and Push
      uses: stefanzweifel/git-auto-commit-action@v5.1.0
      with:
        # Commit message
        commit_message: Build and Commit Release # optional, default is Apply automatic changes
    # Git branch name, where changes should be pushed too. Required if Action is used on the `pull_request` event
        branch: main # optional, default is ${{ github.head_ref }}
    # Email address used for the commit user
        commit_user_email: juanchopanchoaalva@gmail.com # optional, default is 41898282+github-actions[bot]@users.noreply.github.com
    # Value used for the commit author. Defaults to the username of whoever triggered this workflow run.
        commit_author: Curnaleo
    
